# Profile -> 2 types of profile of Spring Boot project -> Development and Production
# It is the development profile of this project
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

  main:
    allow-circular-reference: true

  redis:
    #host: localhost
    #port: 6379
    #url: redis://default:bpW3I3kpi9AY3huUNerkzj9YRySI6YAW@redis-14759.c276.us-east-1-2.ec2.redns.redis-cloud.com:14759
    host: redis-14759.c276.us-east-1-2.ec2.redns.redis-cloud.com
    port: 14759
    password: bpW3I3kpi9AY3huUNerkzj9YRySI6YAW

  data:
    mongodb:
      uri: mongodb+srv://dasdebarghya586:journalApp@cluster0.xi7kwbj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: dasdebarghya586@gmail.com
    password: rucm bhhn hirf wwrk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9090
  # servlet:
    # context-path: /journal