# Profile -> 2 types of profile of Spring Boot project -> Development and Production
# It is the default profile of this project
spring:
  profiles:
    active: dev
  # active: prod
  # active: dev, prod

# Logback customization for debug and trace
logging:
  level:
    net.engineeringdigest.journalapp: DEBUG
    org.springframework.web: TRACE

#To off all logs from the root directory
#logging:
#  level:
#    root: OFF

# to hide the api key for GitHub using the property of .yml file
weather:
  api:
    key: 3199aa34bb6f0027d60d7e4ccb134f32

# another property name for the api value
# weather_api_key: 3199aa34bb6f0027d60d7e4ccb134f32